apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: devopschallenge
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32369
