apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: devopschallenge
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx        # ← ekle
  rules:
  - host: app.127.0.0.1.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 52369
