apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: devopschallenge
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels: { app: frontend }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      containers:
        - name: app
          image: eminekibar/devopschallenge-frontend:manual
          resources:
            requests:
              cpu: "100m"        # HPA hedef yüzdesi bunun üzerinden hesaplanır
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:52369"
            - name: BACKEND_URL
              value: "http://backend:11130"
          ports: [{ containerPort: 52369 }]
          readinessProbe:
            httpGet: { path: "/", port: 52369 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: "/", port: 52369 }
            initialDelaySeconds: 15
            periodSeconds: 20
        - name: loader
          image: busybox:1.36
          command: ["sh","-c","sleep 360000"]  # İhtiyaç olduğunda CPU yükü vereceğiz
          resources:
            requests:
              cpu: "50m"        # HPA hedef yüzdesi bunun üzerinden hesaplanır
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"